src/objects/Config__mdt.object
<CustomObject>
    <description>Configuration for alerts</description>
    <label>Config</label>
    <pluralLabel>Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Config__mdt/fields/Severe__c.field-meta.xml
<CustomField>
    <fullName>Severe__c</fullName>
    <description>Expressed in decimals (0.1 for 10%), when this % is reached/crossed, raise a SEVERE event</description>
    <inlineHelpText>Expressed in decimals (0.1 for 10%), when this % is reached/crossed, raise a SEVERE event</inlineHelpText>
    <label>Severe %</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Config__mdt/fields/Warning__c.field-meta.xml
<CustomField>
    <fullName>Warning__c</fullName>
    <description
	>Expressed in decimals (0.1 for 10%), when this % is reached/crossed, raise a WARNING event</description>
    <inlineHelpText
	>Expressed in decimals (0.1 for 10%), when this % is reached/crossed, raise a WARNING event</inlineHelpText>
    <label>Warning %</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AlertManagerSchedulable.cls
global class AlertManagerSchedulable implements BaseScheduler.ISchedule {
	global void execute(SchedulableContext sc) {
		List<Config__mdt> monitoringConfig = [
			SELECT Id, MasterLabel, Warning__c, Severe__c
			FROM Config__mdt
			LIMIT 1000
		];
		Alert limitsAlert = new LimitsAlert(monitoringConfig);
		if (limitsAlert.shouldAlert()) {
			AlertInvoker slack = new SlackAlertInvoker();
			slack.invokeAlert(limitsAlert.getMessages());
		}
	}
}